### ISSUE TITLE
Redis cache helper can't serialize forum view/post graphs

### ISSUE THREAD

**Issue by jeffputz** [POPWorldMedia/POPForums#168]
NotSupportedException: The collection type 'System.Collections.Generic.Dictionary`2[System.Int32,System.String]' is not supported.
```
   at System.Text.Json.JsonClassInfo.GetElementType(Type propertyType, Type parentType, MemberInfo memberInfo, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, Type implementedPropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.AddPolicyProperty(Type propertyType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.WriteStackFrame.Initialize(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCore(Utf8JsonWriter writer, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCore(PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCoreString(Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at PopForums.AzureKit.Redis.CacheHelper.SetLongTermCacheObject(String key, Object value) in C:\Users\jeffy\Desktop\dev\POPForums\src\PopForums.AzureKit\Redis\CacheHelper.cs:line 102
```

**Comment by jeffputz** [comment]
This is a known and unfortunate problem with `System.Text.Json` serializer.
https://github.com/dotnet/corefx/issues/40120

**Comment by jeffputz** [comment]
Fix and revert in:
c4a824d53750309bfe485219302846d6b84d5dd9
