### ISSUE TITLE
Setup doesn't work in v14 Core

### ISSUE THREAD

**Issue by jeffputz** [POPWorldMedia/POPForums#87]
There are database calls, even though the database has nothing in it yet, so it breaks. This is probably in large part due to the different ways that we do auth now, and it makes it impossible to use the PF ignore attribute on the actions that used to short circuit the auth pipeline in the old MVC version.

**Comment by TheYorkshireDev** [comment]
Is this the specific error you are referring too? When I run the latest on master (90bc8c3d3009be9e81a1423d5ba3a976f2cf64a4) I encounter this issue regardless of the page I am trying to access.

```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at PopForums.Mvc.Areas.Forums.Authorization.PopForumsAuthorizationMiddleware.InvokeAsync(HttpContext context, IUserService userService, IProfileService profileService) in E:\Projects\POPForums\src\PopForums.Mvc\Areas\Forums\Authorization\PopForumsAuthorizationMiddleware.cs:line 20
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_1.<UseMiddleware>b__2(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()

Inner Exception 1:
InvalidOperationException: No authentication handlers are registered. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("PopForumsAuthScheme",...)?
```

**Note:** I have an empty `popforums14` database.

**Comment by jeffputz** [comment]
That's the symptom, but it comes because startup items don't complete due to the lack of a PF tables in the database, so because they don't complete, the auth handler doesn't exist when it runs into it later.
